apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gradle-cache.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gradle-cache.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gradle-cache.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gradle-cache.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "gradle-cache.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: config-mounter
          image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}"
          command:
             - sh
             - -ce
             - mkdir -p /data/conf/ && cp /tmp/config.yaml /data/conf/config.yaml
          volumeMounts:
            - name: tmp-build-cache-config-file
              mountPath: /tmp
            - name: cache
              mountPath: /data
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "gradle-cache.tag" . }}"
          args: {{ .Values.args | toYaml | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5071
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          volumeMounts:
            - name: cache
              mountPath: /data
      volumes:
        - name: tmp-build-cache-config-file
          secret:
            secretName: {{ include "gradle-cache.configSecretName" . }}
        {{- .Values.volumes | toYaml | nindent 8 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
